apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm3
  namespace: wireguard-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm3
  template:
    metadata:
      labels:
        app: vm3
    spec:
      containers:
      - name: wireguard
        image: linuxserver/wireguard
        env:
        - name: TZ
          value: "UTC"
        volumeMounts:
        - name: config
          mountPath: /config
        ports:
        - containerPort: 51820
          protocol: UDP
      volumes:
      - name: config
        configMap:
          name: wireguard-config
          items:
          - key: wg3.conf
            path: wg0.conf
